/**
 * LLM Provider Interface - Abstraction for language model providers
 *
 * Per PLAN.md Phase 5:
 * We will build an interface that supports hot-swapping models, as requested.
 *
 * ```typescript
 * interface LLMProvider {
 *     streamResponse(
 *         context: string,
 *         modelId: string
 *     ): AsyncGenerator<string, void, unknown>;
 * }
 * ```
 */

// ============================================================================
// LLM Provider Interface
// ============================================================================

/**
 * Interface for LLM providers supporting streaming responses
 *
 * Implementations must provide a streaming generator that yields tokens
 * as they are generated by the model.
 */
export interface LLMProvider {
  /**
   * Stream a response from the LLM given conversation context
   *
   * @param context - The conversation context (transcript text)
   * @param modelId - The model identifier to use
   * @yields Token chunks as they are generated
   */
  streamResponse(
    context: string,
    modelId: string
  ): AsyncGenerator<string, void, unknown>;

  /**
   * Get the provider name for identification
   */
  readonly name: string;

  /**
   * Check if the provider is configured and ready to use
   */
  isConfigured(): boolean;

  /**
   * Get the default model ID for this provider
   */
  getDefaultModelId(): string;

  /**
   * Get available model IDs for this provider
   */
  getAvailableModels(): string[];
}

// ============================================================================
// Response Types
// ============================================================================

/**
 * Metadata about an LLM response
 */
export interface LLMResponseMetadata {
  /** Model used for generation */
  modelId: string;
  /** Provider name */
  provider: string;
  /** Estimated input tokens */
  inputTokens?: number;
  /** Estimated output tokens */
  outputTokens?: number;
  /** Generation time in milliseconds */
  durationMs?: number;
}

/**
 * Complete response from an LLM including metadata
 */
export interface LLMResponse {
  /** The generated text */
  text: string;
  /** Response metadata */
  metadata: LLMResponseMetadata;
}

// ============================================================================
// Error Types
// ============================================================================

/**
 * Error thrown by LLM providers
 */
export class LLMError extends Error {
  constructor(
    message: string,
    public readonly code: string,
    public readonly provider: string,
    public readonly cause?: Error
  ) {
    super(message);
    this.name = 'LLMError';
  }
}

/**
 * Error codes for LLM operations
 */
export const LLM_ERROR_CODES = {
  NOT_CONFIGURED: 'NOT_CONFIGURED',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_MODEL: 'INVALID_MODEL',
  CONTEXT_TOO_LONG: 'CONTEXT_TOO_LONG',
  API_ERROR: 'API_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  STREAM_ERROR: 'STREAM_ERROR',
} as const;

export type LLMErrorCode = (typeof LLM_ERROR_CODES)[keyof typeof LLM_ERROR_CODES];
