export const IPC = {
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  settingsOpen: 'settings:open',
  permStatus: 'perm:status',
  permRequestMic: 'perm:request-mic',
  permOpenScreenPrefs: 'perm:open-screen-prefs',
  transcriptionStart: 'transcription:start',
  transcriptionStop: 'transcription:stop',
  transcriptionStatus: 'transcription:status',
  audioChunk: 'audio:chunk',
  transcriptUpdate: 'transcript:update',
  transcriptSnapshot: 'transcript:snapshot',
  transcriptClear: 'transcript:clear',
  llmTrigger: 'llm:trigger',
  llmStart: 'llm:start',
  llmAbort: 'llm:abort',
  llmToken: 'llm:token',
  llmDone: 'llm:done',
  llmError: 'llm:error',
  visionTrigger: 'vision:trigger',
  visionStart: 'vision:start',
  visionAbort: 'vision:abort',
  windowToggle: 'window:toggle',
  windowSetMode: 'window:set-mode',
  windowModeChanged: 'window:mode-changed',
  windowVisibilityChanged: 'window:visibility-changed',
  windowFocusState: 'window:focus-state',
  windowUserActive: 'window:user-active',
  windowQuit: 'window:quit',
  toast: 'ui:toast',
  socketStatus: 'socket:status',
  presetsGet: 'presets:get',
  presetsSetActive: 'presets:set-active',
  presetsSetOverride: 'presets:set-override',
  presetsChanged: 'presets:changed',
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
